name: CI
on: [pull_request, push]

permissions: {}

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install tools
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build
